apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-feature-discovery.fullname" . }}-master
  labels:
    {{- include "node-feature-discovery.labels" . | nindent 4 }}
    role: master
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - port: {{ .Values.master.service.port }}
      targetPort: gRPC
      protocol: TCP
      name: gRPC
  selector:
    {{- include "node-feature-discovery.selectorLabels" . | nindent 4 }}
