name: Release Charts

on: [push]
  # push:
  #   branches:
  #     - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Configure Helm
        uses: azure/setup-helm@v1
        # with:
        #   version: '<version>' # default is latest stable
        # id: install

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        with:
          charts_dir: deploy/chart
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
